### ISSUE TITLE
Model is not updated when I change

### ISSUE THREAD

**Issue by ChrisLHT** [teamcancode/ngx-form-control#1]
Actually , your ngx-form-control is really amazing , but it still has a problem

I was using an array as model , when i remove an object in it , it is updated , but when i push another one , it would never be updated.

 I don't know why but i need a help . So seriously now . Thank you !!

**Comment by teamcancode** [comment]
Hi Chris, thanks again for your feedback.

This is small problem when we use ngModel as object or array. I'll update this problem soon.
For now, we must reassign ngModel when we update it (because it's array), example:
- remove: data = data.filter((item) => item.id !== 2);
- add: data = [...data, newItem]

**Comment by ChrisLHT** [comment]
Thank you , it works for me !
